
name: All Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  unit-tests:
    needs: [lint]
    uses: ./.github/workflows/unit-tests.yml

  integration-tests:
    needs: [lint]
    uses: ./.github/workflows/integration-tests.yml

  playwright:
    needs: [unit-tests, integration-tests]
    uses: ./.github/workflows/playwright.yml
